### ISSUE TITLE
Vcs-server crashes when loading certain variables

### ISSUE THREAD

**Issue by James-Crean** [UV-CDAT/vcs-js#19]
In FileLoader.py, line 45, the code tests if the variable has a longitude, but does not test for a latitude. The code then goes on to call 
```
lonName = var.getLongitude().id
latName = var.getLatitude().id
```
If a variable has a longitude, but does not have a latitude, getLatitude() will return None, and trying to access .id will result in an exception. 

Example: The navy_land.nc data file has the variable "bounds_lon" which produces this error.

**Comment by danlipsa** [comment]
@James-Crean @doutriaux1 Can you attach your test data to this bug report: ta_ncep_87-6-88-4.nc or navy_land.nc? Thanks!

**Comment by doutriaux1** [comment]
@danlipsa just run
```
vcs_download_sample_data
```

**Comment by doutriaux1** [comment]
navy_land might be in share/cdutil

**Comment by danlipsa** [comment]
@doutriaux1 Great. Thanks. I'll take a look.
