### ISSUE TITLE
Clear function doesn't seem to work

### ISSUE THREAD

**Issue by James-Crean** [UV-CDAT/vcs-js#21]
Calling canvas.clear() does not seem to work.

The vcs demo has a clear button/link that calls vcs_boxfill_clear(), but clicking it does not do anything for me. No errors are raised in the developer tools, nor is there any output by the vcs server.

**Comment by mattben** [comment]
👍

**Comment by danlipsa** [comment]
I think this is again a difference between on-screen and off-screen rendering. I think on-screen works fine. I'll soon be back working on cdat I understand and I'll look into this.

**Comment by James-Crean** [comment]
@danlipsa  Have you had a chance to take a look at this yet?
