### ISSUE TITLE
Unable to plot after clear

### ISSUE THREAD

**Issue by James-Crean** [UV-CDAT/vcs-js#26]
I am unable to get a plot to render in the same canvas after I have done a plot followed by a clear.

Steps to reproduce:
* Plot a default boxfill with clt
* Clear the canvas
* Plot again _-This plot fails_

I checked through the vcdat code and didn't find anything that seemed to be causing it, and the arguments being passed to plot are valid.

**Comment by danlipsa** [comment]
@scottwittenburg I think this is similar with 'plotting a boxfill (colormaping on a scalar) followed by plotting a vector' = the correct image is produced on the server by the image does not get to the client.

**Comment by James-Crean** [comment]
Yes, that is the sort of behavior I have been seeing.
