### ISSUE TITLE
create a method getgraphicsmethodvariablecount

### ISSUE THREAD

**Issue by danlipsa** [UV-CDAT/vcs-js#29]
In Visualizer.py we have getgraphicsmethodtypes which returns all graphics method types. getgraphicsmethodvariablecount(type) should return how many variables that graphics method type expects.

For instance, this will return 1 for boxfill but 2 for vector and streamlines.

@doutriaux1 Any luck in locating this method in vcs? If you find it we will use a similar name in vcs-js. I looked for it but could not find it.

@scottwittenburg If we cannot find this, we could probably add it to vcs and vcs-js.

**Comment by doutriaux1** [comment]
@danlipsa I'm still looking. I know it's there. I'm "pretty" sure.

**Comment by doutriaux1** [comment]
got it: https://github.com/UV-CDAT/vcs/blob/master/vcs/xmldocs.py#L559

**Comment by danlipsa** [comment]
Nice. Thanks @doutriaux1 So @scottwittenburg we need to cal the following on the server. Let me know if you have any questions.
<pre>
>>> vcs.xmldocs.obj_details['graphics method']['vector']['slabs']
2
>>> vcs.xmldocs.obj_details['graphics method']['boxfill']['slabs']
1
>>> vcs.xmldocs.obj_details['graphics method']['streamline']['slabs']
2
</pre>

**Comment by scottwittenburg** [comment]
Thanks @danlipsa, will do.
