### ISSUE TITLE
Why is vcs-js exposing jquery and ndarray?

### ISSUE THREAD

**Issue by scottwittenburg** [UV-CDAT/vcs-js#32]
Does anyone know why we're exposing those libraries in our built javascript?  It seems `vcs-js` itself can do completely without `jQuery`, so I'd like to remove that dependency from the project.  It looks like `ndarray` is being used in some of our javascript, so I wouldn't get rid of that, but I am curious why we're exposing and if we can stop.

**Comment by doutriaux1** [comment]
vcswidgets maybe?

**Comment by scottwittenburg** [comment]
Well, `VCS-widgets` seems to actually use jQuery (albeit in only one file where it may not even be necessary).  So rather than listing it as a `peerDependency`, it should probably be an actual `dependency` there, and not count on this project bringing it along.

To me it still seems we should remove it from this project.  But I'm open to arguments :smile:

**Comment by scottwittenburg** [comment]
I removed the exposed jQuery in #33, closing this.
