### ISSUE TITLE
linux/travis test suite fails

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcs-js#39]
https://travis-ci.org/UV-CDAT/vcs-js/builds/346953511?utm_source=github_status&utm_medium=notification

**Comment by scottwittenburg** [comment]
@doutriaux1 Out of curiosity, did you just re-trigger some old travis builds?  I'm trying to understand the build history I'm seeing, but it's weird because some tests seem to have run an hour ago, but the related branches were merged months ago or more.

**Comment by scottwittenburg** [comment]
Should we close this now, @doutriaux1?  We can always re-open it if the problem surfaces again at some point.
