### ISSUE TITLE
Star the repo

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/vcs-js#4]
Folks, currently we have zero stars on this repo. Alleast the developers could start it 😄

**Comment by aashish24** [comment]
@mattben could you please star the repo? At least core developers could star the repo; it increases the awareness on the project. Let's discuss it if you have any suggestions otherwise until then let's keep it open. I would like to discuss this in our next meeting and then we can close it.

**Comment by mattben** [comment]
🎃 👍

**Comment by aashish24** [comment]
thanks @mattben
